# ============================================================
# Internship Portal - main file
#
# The database models (tables) are in models.py.
# The code for the pages lives in the routes/ folder:
#   routes/auth.py       -> register + login + logout
#   routes/main.py       -> landing page + dashboard + internship list
#   routes/student.py    -> apply, my applications, weekly logs
#   routes/company.py    -> post/edit/delete internships, applicants
#   routes/supervisor.py -> my students, view logs, give feedback
#   routes/admin.py      -> manage users
#
# Below, app.add_url_rule() connects every URL of the site
# to its function - like a table of contents of the whole app.
# ============================================================

import os
from flask import Flask
from flask_wtf.csrf import CSRFProtect
from models import db

app = Flask(__name__)

# Secret key: signs the session cookie and the CSRF tokens.
# In a real deployment this comes from the environment, never from the source.
app.secret_key = os.environ.get('SECRET_KEY', 'my-secret-key')

# CSRF protection: every POST form must carry a token generated by the server,
# so another website cannot submit a form on behalf of a logged-in user.
csrf = CSRFProtect(app)

# ---------- database connection (SQLAlchemy + PyMySQL) ----------
# The tests point this at a separate test database through the DATABASE_URL
# environment variable; normally the line below is used.
app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get(
    'DATABASE_URL',
    'mysql+pymysql://root:password@localhost/internship_db')   # <-- change 'password' to your MySQL password
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db.init_app(app)

# folder where student documents are saved
os.makedirs(os.path.join(app.root_path, 'static', 'uploads'), exist_ok=True)

from routes import main, auth, student, company, supervisor, admin

# make the logo available to every template if the file has been added
@app.context_processor
def inject_logo():
    logo = os.path.join(app.root_path, 'static', 'logo.png')
    return {'has_logo': os.path.exists(logo)}


# make the verification state of the logged-in user, and the number of
# accounts waiting for approval, available to every template
@app.context_processor
def inject_verification():
    from flask import session
    from models import User
    data = {'my_status': None, 'my_remarks': None, 'pending_count': 0}
    if session.get('user_id'):
        user = db.session.get(User, session['user_id'])
        if user:
            data['my_status'] = user.verification_status
            data['my_remarks'] = user.verification_remarks
        if session.get('role') == 'admin':
            data['pending_count'] = (User.query
                                     .filter_by(verification_status='pending')
                                     .filter(User.role_id != 1).count())
    return data


# make the unread notification count available to every template (bell icon)
@app.context_processor
def inject_unread_count():
    from flask import session
    from models import Notification
    if session.get('user_id'):
        count = Notification.query.filter_by(user_id=session['user_id'],
                                             is_read=False).count()
        return {'unread_count': count}
    return {'unread_count': 0}

# ---------- home + dashboard + internship list ----------
app.add_url_rule('/',            view_func=main.home)
app.add_url_rule('/dashboard',   view_func=main.dashboard)
app.add_url_rule('/internships', view_func=main.internships)

# ---------- register + login + logout ----------
app.add_url_rule('/register',            view_func=auth.register)
app.add_url_rule('/register/student',    view_func=auth.register_student,    methods=['GET', 'POST'])
app.add_url_rule('/register/company',    view_func=auth.register_company,    methods=['GET', 'POST'])
app.add_url_rule('/register/supervisor', view_func=auth.register_supervisor, methods=['GET', 'POST'])
app.add_url_rule('/login',  view_func=auth.login, methods=['GET', 'POST'])
app.add_url_rule('/logout', view_func=auth.logout)

# ---------- student pages ----------
app.add_url_rule('/apply/<int:internship_id>',    view_func=student.apply,    methods=['POST'])
app.add_url_rule('/my_applications',              view_func=student.my_applications)
app.add_url_rule('/withdraw/<int:id>',            view_func=student.withdraw, methods=['POST'])
app.add_url_rule('/my_logs/<int:application_id>', view_func=student.my_logs,  methods=['GET', 'POST'])

# ---------- company pages ----------
app.add_url_rule('/internships/add',             view_func=company.add_internship,    methods=['GET', 'POST'])
app.add_url_rule('/internships/edit/<int:id>',   view_func=company.edit_internship,   methods=['GET', 'POST'])
app.add_url_rule('/internships/delete/<int:id>', view_func=company.delete_internship, methods=['POST'])
app.add_url_rule('/applicants/<int:internship_id>', view_func=company.applicants)
app.add_url_rule('/applications/<int:id>/status',   view_func=company.update_status, methods=['POST'])

# ---------- supervisor pages ----------
app.add_url_rule('/students',                   view_func=supervisor.students)
app.add_url_rule('/logs/<int:application_id>',  view_func=supervisor.view_logs)
app.add_url_rule('/logs/<int:log_id>/feedback', view_func=supervisor.give_feedback, methods=['POST'])

# ---------- admin pages ----------
app.add_url_rule('/users',                 view_func=admin.users)
app.add_url_rule('/users/delete/<int:id>', view_func=admin.delete_user, methods=['POST'])
app.add_url_rule('/users/export',          view_func=admin.users_export)
app.add_url_rule('/audit',                 view_func=admin.audit_log)
app.add_url_rule('/verifications',         view_func=admin.verifications)
app.add_url_rule('/verify/<int:id>',       view_func=admin.verify_user, methods=['POST'])
app.add_url_rule('/reject/<int:id>',       view_func=admin.reject_user, methods=['POST'])
app.add_url_rule('/colleges',              view_func=admin.colleges, methods=['GET', 'POST'])
app.add_url_rule('/colleges/delete/<int:id>', view_func=admin.delete_college, methods=['POST'])

# ---------- notifications ----------
app.add_url_rule('/notifications', view_func=main.notifications)

# ---------- csv exports ----------
app.add_url_rule('/applicants/<int:internship_id>/export', view_func=company.applicants_export)
if __name__ == '__main__':
    app.run(debug=True)
